### ISSUE TITLE
Question about organisations on GitHub

### ISSUE THREAD

**Issue by StevenPuttemans** [StevenPuttemans/opencv#6]
Hi @alalek and @mshabunin I guess that due to the buyout of Itseez by intel, that the repo name had to change. This led to the removal of wiki editing rights and such. Just wondering if Intel decided to keep the organisation clear of volunteers or if people are going to be added again? 

Drop me a note here when you got the time! No rush :)

**Comment by vpisarev** [comment]
@StevenPuttemans,
Here I express my personal opinion.

OpenCV became what it is now largely because of the great community involvement, especially since 2008-2009. Intel understand it and I doubt they want to get back to the closed development model. Therefore, I believe that all the infrastructure will stay open and the access to wiki should be restored within a few weeks from now. It's just that now we are in the middle of transition period, where many little and big things happened or will happen soon - new hardware, new e-mails, new servers etc. It should be over in a month or two and after that, I believe, we all (the core team and the contributors) will get back to our normal workflow.

**Comment by StevenPuttemans** [comment]
@vpisarev great to hear that! Success with the transition and keep us up to date if you need any help!
